# Generated by Django 4.2 on 2023-04-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_levels_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
