# Generated by Django 4.2 on 2023-04-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_genero_remove_clientes_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='escucho_de',
        ),
    ]
