# Generated by Django 4.2 on 2023-04-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_remove_clientes_escucho_de'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='image_source',
        ),
    ]
