# Generated by Django 4.2 on 2023-04-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_clientes_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='estado_civil',
        ),
    ]
