# Generated by Django 4.2 on 2023-04-24 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_remove_clientes_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='posApp.clientes'),
            preserve_default=False,
        ),
    ]
