# Generated by Django 4.2 on 2023-04-24 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_sales_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='client',
        ),
    ]
