# Generated by Django 4.2 on 2023-05-12 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0017_formapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='tipoPago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posApp.formapago'),
            preserve_default=False,
        ),
    ]
