# Generated by Django 4.2 on 2024-10-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0022_alter_sales_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
