# Generated by Django 4.2 on 2024-10-05 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0027_category_sucursal_clientes_sucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='estado_mensualidad',
            field=models.CharField(default='Sin mensualidades', max_length=20),
        ),
        migrations.AddField(
            model_name='clientes',
            name='plan_inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posApp.planinscripcion'),
        ),
    ]
