# Generated by Django 4.2 on 2024-10-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0028_clientes_estado_mensualidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
