# Generated by Django 4.2 on 2024-10-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0029_salesitems_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitems',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posApp.products'),
        ),
    ]
