# Generated by Django 4.2 on 2024-10-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0030_alter_salesitems_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='levels',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posApp.sucursal'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
