# Generated by Django 4.2 on 2025-01-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0031_levels_sucursal_alter_levels_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
