# Generated by Django 4.2 on 2025-06-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0032_products_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posApp.clientes'),
        ),
    ]
