# Generated by Django 4.2 on 2025-06-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0034_alter_sales_date_added_alter_sales_tipopago'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['sucursal', 'date_added'], name='sales_sucursal_date_idx'),
        ),
    ]
