# Generated by Django 4.2 on 2025-07-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0035_sales_sales_sucursal_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_modelo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_modelo_manager',
            field=models.BooleanField(default=False),
        ),
    ]
